### PR TITLE
Main Navbar Translation

### PR DESCRIPTION
**Pull request by baruchvlz**
Translate the main nav partial. I'm not 100% sold on `Features` being translated to `Características` but I couldn't find a better word in the thesaurus.

### CODE REVIEW

**Comment by baruchvlz** [comment]
Signed!

**Comment by baruchvlz** [comment]
Signed with correct email.

**Comment by baruchvlz** [comment]
@Foxandxss Hey Jesús, how can I fix my CLA?

**Comment by Foxandxss** [comment]
You need to amend your commit to use your account.

First check that your git in your machine has your username and email.

Then you can change the author of your commit.

You can do `git commit --amend --autor="Your name your@email.com"

Then force push to your fork and branch.

And important, don't use your master, create a branch for each new PR.

**Comment by baruchvlz** [comment]
Thanks for explaining. You think it's better to close this and I'll open a new PR with the correct email and branch?

**Comment by Foxandxss** [comment]
That works too.

**Pull request closed without merging**
